version: "3.9"

services:
  flyway_mysql:
    image: boxfuse/flyway:latest
    command: "migrate"
    environment:
      FLYWAY_USER: root
      FLYWAY_PASSWORD: root
      FLYWAY_URL: jdbc:mysql://db:3306/freesia
    volumes:
      - ./docker/migrations/sql:/flyway/sql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: freesia
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - 3306