version: "3.9"

services:

  liquibase:
    image: liquibase/liquibase
    container_name: liquibase
    depends_on:
      - db
    hostname: liquibase
    environment:
      MYSQL_DB: db
    volumes:
      - ./config/db:/liquibase/changelog
#    command: [
#        '-c',
#        './liquibase_policy_init.sh',
#        'db', '3306'
#    ]

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: freesia
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
