version: "3.9"

services:

  liquibase:
    image: liquibase-mysql:build
    container_name: liquibase
    depends_on:
      - db
    hostname: liquibase
    environment:
      MYSQL_DB: db
    volumes:
      - ./config/db:/liquibase/changelog
    entrypoint: ./wait_for_port.sh
    command: [
        '-c',
        './liquibase_policy_init.sh',
        'db', '3306'
    ]

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: Freesia21
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
